CREATE TABLE `book` (
  `BOOK_ID` varchar(50) NOT NULL,
  `BOOK_NAME` varchar(100) DEFAULT NULL,
  `AUTHOR` varchar(100) DEFAULT NULL,
  `AVAILABLE_COPIES` int DEFAULT NULL,
  `TOTAL_COPIES` int DEFAULT NULL,
  PRIMARY KEY (`BOOK_ID`)
) ;